// Generated by CoffeeScript 1.3.1
(function() {
  var Kache, Spine;

  Spine = this.Spine || require('spine');

  Kache = this.Kache || require('kache');

  Spine.Model.Kache = {
    init: function() {
      return this.cache = Kache(this.className);
    },
    extended: function() {
      this.change(this.set);
      return this.fetch(this.get);
    },
    get: function() {
      var result;
      result = this.cache.get(this.className);
      return this.refresh(result || [], {
        clear: true
      });
    },
    isEnabled: function() {
      return Kache.isEnabled();
    },
    set: function() {
      if (this.isEnabled()) {
        return this.cache.set(this.className, result);
      }
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Kache;
  }

}).call(this);
