// Generated by CoffeeScript 1.3.1
(function() {
  var Kache, Spine;

  Spine = this.Spine || require('spine');

  Kache = this.Kache || require('kache');

  Spine.Model.Kache = {
    extended: function() {
      this.change(this.setKache);
      return this.fetch(this.loadKache);
    },
    loadKache: function() {
      var result;
      this.cache = Kache(this.className);
      result = this.cache.get(this.className);
      return this.refresh(result || [], {
        clear: true
      });
    },
    setKache: function() {
      if (Kache.isEnabled()) {
        this.cache = Kache(this.className);
        return this.cache.set(this.className, this);
      }
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Kache;
  }

}).call(this);
